In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size 
voc_size = 10000

In [5]:
# One hot representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]

In [6]:
one_hot_repr

[[230, 9097, 4779, 2343],
 [230, 9097, 4779, 9383],
 [230, 5064, 4779, 5927],
 [6062, 7214, 634, 321, 9827],
 [6062, 7214, 634, 321, 8532],
 [761, 230, 3435, 4779, 9890],
 [2885, 3346, 637, 321]]

In [8]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0  230 9097 4779 2343]
 [   0    0    0    0  230 9097 4779 9383]
 [   0    0    0    0  230 5064 4779 5927]
 [   0    0    0 6062 7214  634  321 9827]
 [   0    0    0 6062 7214  634  321 8532]
 [   0    0    0  761  230 3435 4779 9890]
 [   0    0    0    0 2885 3346  637  321]]


In [12]:
# Feature representation
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [16]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step


array([[[ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.01754962,  0.02279139,  0.04908706, -0.04750466,
          0.03637817, -0.04236588,  0.0312818 ,  0.03916942,
         -0.02768168, -0.02581735],
        [ 0.02836229, -0.04504999,  0.0272978 ,  0.03351492,
          0.02111552,  0.02408801,  0.04872446,  0.00704535,
         -0.03698857, -0.02860727],
        [ 0.00486046, -0.03171398, -0.04835956,  0.0

In [18]:
embedding_docs[0]

array([   0,    0,    0,    0,  230, 9097, 4779, 2343])

In [20]:
embedding_docs_0 = np.array([embedding_docs[0]])
model.predict(embedding_docs_0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.03242456,  0.01637173,  0.03639083,  0.04511955,
          0.02156571,  0.04130436, -0.03681868,  0.00744274,
          0.01204305, -0.0414478 ],
        [ 0.01754962,  0.02279139,  0.04908706, -0.04750466,
          0.03637817, -0.04236588,  0.0312818 ,  0.03916942,
         -0.02768168, -0.02581735],
        [ 0.02836229, -0.04504999,  0.0272978 ,  0.03351492,
          0.02111552,  0.02408801,  0.04872446,  0.00704535,
         -0.03698857, -0.02860727],
        [ 0.00486046, -0.03171398, -0.04835956,  0.0